version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/docker/craftcli'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/docker/craftcms'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/docker/composer'
    schedule:
      interval: 'weekly'
    
  - package-ecosystem: 'docker'
    directory: '/docker/postgres'
    schedule:
      interval: 'weekly'
  
  - package-ecosystem: 'docker'
    directory: '/docker/redis'
    schedule:
      interval: 'weekly'
